apiVersion: v1
kind: ReplicationController
metadata:
  name: rcgaggi
spec:
  replicas: 5
  selector:
    name:  chanchal
  template:
    metadata:
      name: rcpod
      labels:
        name: chanchal
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
