apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix
  namespace: gagan
spec:
  selector:
    matchLabels:
      env: prod    
  template:
    metadata:
      labels:
        env: prod
    spec:
      containers:
      - name: netflix
        image: devopsinsiders/netflix
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 80
