apiVersion: v1
kind: Pod
metadata:
  name: gaganpod
  labels:
    env: dev
spec:
  containers:
  - name: gagancontainer
    image: nginx
    # resources:
    #   limits:
    #     memory: "128Mi"
    #     cpu: "500m"
    ports:
      - containerPort: 80
